name: Send Daily UPSC AI Brief

on:
  schedule:
    # Runs every day at 03:00 UTC (08:30 AM IST)
    - cron: "0 3 * * *"
  workflow_dispatch:  # allows manual trigger

jobs:
  run-generator:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: 🧭 Checkout repository
        uses: actions/checkout@v4

      - name: 🐍 Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: 📦 Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install feedparser newspaper3k reportlab openai requests pillow readability-lxml

      - name: ⚙️ Generate and Send UPSC Brief
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          SMTP_HOST: smtp.gmail.com
          SMTP_PORT: 587
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
        run: python generate_and_send.py