on:
  schedule:
    - cron: "48 7 * * *"   # runs daily at 1:18 PM IST (07:48 UTC)
  workflow_dispatch:

jobs:
  send-mail:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install reportlab

      - name: Generate & email PDF
        env:
          SMTP_HOST: smtp.gmail.com
          SMTP_PORT: 587
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
        run: python email_pdf_service.py